### ISSUE TITLE
如何使用包

### ISSUE THREAD

**Issue by 1029855168** [SunshowerC/fund-strategy#2]
没有js文件 怎么运行？？？ 初学者发问

**Comment by SunshowerC** [comment]
> 没有js文件 怎么运行？？？ 初学者发问

在 nodejs 环境运行：
```
npm install
npm start 
```

**Comment by 1029855168** [comment]
谢谢大佬！！！ 已经跑通了！





------------------ 原始邮件 ------------------
发件人: 晨微雨 <notifications@github.com&gt;
发送时间: 2021年1月14日 01:16
收件人: SunshowerC/fund-strategy <fund-strategy@noreply.github.com&gt;
抄送: 1029855168 <www.1029855168@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[SunshowerC/fund-strategy] 如何使用包 (#2)





  
没有js文件 怎么运行？？？ 初学者发问
  
在 nodejs 环境运行：
 npm install npm start
